version: "3.8"

services:
  web:
    build:
      context: .
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: dummykey123
    ports:
      - "3000:3000"
    command: ./bin/rails server -b 0.0.0.0
