default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("PGUSER", "postgres") %>
  password: <%= ENV.fetch("PGPASSWORD", "") %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  pool: 5

development:
  <<: *default
  database: jesus_restaura_development

test:
  <<: *default
  database: jesus_restaura_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  sslmode: require # optional, can be removed if Dokku errors on SSL
